// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIActionButton : GButton
    {
        private GGraph m_Up;
        public GGraph Up => this.m_Up;
        private GGraph m_Over;
        public GGraph Over => this.m_Over;
        private GGraph m_Down;
        public GGraph Down => this.m_Down;
        public const string URL = "ui://oozeu71hi20a7";

        public static UIActionButton CreateInstance()
        {
            return (UIActionButton)UIPackage.CreateObject("Package1", "ActionButton");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Up = (GGraph)GetChild("up");
            m_Over = (GGraph)GetChild("over");
            m_Down = (GGraph)GetChild("down");
        }
    }
}