// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UICategoryTabButton : GButton
    {
        private GGraph m_Up;
        public GGraph Up => this.m_Up;
        private GGraph m_Over;
        public GGraph Over => this.m_Over;
        private GGraph m_Selected;
        public GGraph Selected => this.m_Selected;
        public const string URL = "ui://oozeu71hi20a6";

        public static UICategoryTabButton CreateInstance()
        {
            return (UICategoryTabButton)UIPackage.CreateObject("Package1", "CategoryTabButton");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Up = (GGraph)GetChild("up");
            m_Over = (GGraph)GetChild("over");
            m_Selected = (GGraph)GetChild("selected");
        }
    }
}