// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIDialog : GComponent
    {
        private GGraph m_Panel;
        public GGraph Panel => this.m_Panel;
        private GGraph m_Accent;
        public GGraph Accent => this.m_Accent;
        private GTextField m_TitleText;
        public GTextField TitleText => this.m_TitleText;
        private GTextField m_SubtitleText;
        public GTextField SubtitleText => this.m_SubtitleText;
        private GGraph m_Divider;
        public GGraph Divider => this.m_Divider;
        private GTextField m_MessageText;
        public GTextField MessageText => this.m_MessageText;
        private UIActionButton m_OtherButton;
        public UIActionButton OtherButton => this.m_OtherButton;
        private UIActionButton m_CancelButton;
        public UIActionButton CancelButton => this.m_CancelButton;
        private UIActionButton m_ConfirmButton;
        public UIActionButton ConfirmButton => this.m_ConfirmButton;
        public const string URL = "ui://oozeu71hyih6a";

        public static UIDialog CreateInstance()
        {
            return (UIDialog)UIPackage.CreateObject("Package1", "Dialog");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Panel = (GGraph)GetChild("panel");
            m_Accent = (GGraph)GetChild("accent");
            m_TitleText = (GTextField)GetChild("titleText");
            m_SubtitleText = (GTextField)GetChild("subtitleText");
            m_Divider = (GGraph)GetChild("divider");
            m_MessageText = (GTextField)GetChild("messageText");
            m_OtherButton = (UIActionButton)GetChild("otherButton");
            m_CancelButton = (UIActionButton)GetChild("cancelButton");
            m_ConfirmButton = (UIActionButton)GetChild("confirmButton");
        }
    }
}