// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIDialog : GComponent
    {
        private GGraph m_Mask;
        public GGraph Mask => this.m_Mask;
        private GTextField m_TitleText;
        public GTextField TitleText => this.m_TitleText;
        private GTextField m_MessageText;
        public GTextField MessageText => this.m_MessageText;
        private GButton m_ConfirmButton;
        public GButton ConfirmButton => this.m_ConfirmButton;
        private GButton m_CancelButton;
        public GButton CancelButton => this.m_CancelButton;
        private GButton m_OtherButton;
        public GButton OtherButton => this.m_OtherButton;
        public const string URL = "ui://oozeu71hyih6a";

        public static UIDialog CreateInstance()
        {
            return (UIDialog)UIPackage.CreateObject("Package1", "Dialog");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Mask = (GGraph)GetChild("mask");
            m_TitleText = (GTextField)GetChild("titleText");
            m_MessageText = (GTextField)GetChild("messageText");
            m_ConfirmButton = (GButton)GetChild("confirmButton");
            m_CancelButton = (GButton)GetChild("cancelButton");
            m_OtherButton = (GButton)GetChild("otherButton");
        }
    }
}