// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIInventoryItem : GButton
    {
        private GGraph m_Up;
        public GGraph Up => this.m_Up;
        private GGraph m_Over;
        public GGraph Over => this.m_Over;
        private GGraph m_Down;
        public GGraph Down => this.m_Down;
        private GGraph m_RarityBar;
        public GGraph RarityBar => this.m_RarityBar;
        private GTextField m_ItemName;
        public GTextField ItemName => this.m_ItemName;
        private GTextField m_ItemType;
        public GTextField ItemType => this.m_ItemType;
        private GTextField m_ItemCount;
        public GTextField ItemCount => this.m_ItemCount;
        public const string URL = "ui://oozeu71hi20a5";

        public static UIInventoryItem CreateInstance()
        {
            return (UIInventoryItem)UIPackage.CreateObject("Package1", "InventoryItem");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Up = (GGraph)GetChild("up");
            m_Over = (GGraph)GetChild("over");
            m_Down = (GGraph)GetChild("down");
            m_RarityBar = (GGraph)GetChild("rarityBar");
            m_ItemName = (GTextField)GetChild("itemName");
            m_ItemType = (GTextField)GetChild("itemType");
            m_ItemCount = (GTextField)GetChild("itemCount");
        }
    }
}