// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIInventoryView : GComponent
    {
        private Controller m_Category;
        public Controller Category => this.m_Category;
        private GGraph m_Background;
        public GGraph Background => this.m_Background;
        private GGraph m_Topbar;
        public GGraph Topbar => this.m_Topbar;
        private GTextField m_Title;
        public GTextField Title => this.m_Title;
        private GTextField m_Subtitle;
        public GTextField Subtitle => this.m_Subtitle;
        private UIActionButton m_OpenOverlayButton;
        public UIActionButton OpenOverlayButton => this.m_OpenOverlayButton;
        private UIActionButton m_CloseButton;
        public UIActionButton CloseButton => this.m_CloseButton;
        private GGraph m_CategoryPanel;
        public GGraph CategoryPanel => this.m_CategoryPanel;
        private GTextField m_CategoryTitle;
        public GTextField CategoryTitle => this.m_CategoryTitle;
        private UICategoryTabButton m_AllButton;
        public UICategoryTabButton AllButton => this.m_AllButton;
        private UICategoryTabButton m_EquipmentButton;
        public UICategoryTabButton EquipmentButton => this.m_EquipmentButton;
        private UICategoryTabButton m_ConsumableButton;
        public UICategoryTabButton ConsumableButton => this.m_ConsumableButton;
        private UICategoryTabButton m_QuestButton;
        public UICategoryTabButton QuestButton => this.m_QuestButton;
        private GTextField m_ControllerLabel;
        public GTextField ControllerLabel => this.m_ControllerLabel;
        private GTextField m_ControllerPageText;
        public GTextField ControllerPageText => this.m_ControllerPageText;
        private GGraph m_ContentPanel;
        public GGraph ContentPanel => this.m_ContentPanel;
        private GTextField m_ListTitle;
        public GTextField ListTitle => this.m_ListTitle;
        private GTextField m_StatusText;
        public GTextField StatusText => this.m_StatusText;
        private GList m_ItemList;
        public GList ItemList => this.m_ItemList;
        private GGraph m_HintLine;
        public GGraph HintLine => this.m_HintLine;
        private GTextField m_HintText;
        public GTextField HintText => this.m_HintText;
        public const string URL = "ui://oozeu71hi20a2";

        public static UIInventoryView CreateInstance()
        {
            return (UIInventoryView)UIPackage.CreateObject("Package1", "InventoryView");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Category = GetController("category");
            m_Background = (GGraph)GetChild("background");
            m_Topbar = (GGraph)GetChild("topbar");
            m_Title = (GTextField)GetChild("title");
            m_Subtitle = (GTextField)GetChild("subtitle");
            m_OpenOverlayButton = (UIActionButton)GetChild("openOverlayButton");
            m_CloseButton = (UIActionButton)GetChild("closeButton");
            m_CategoryPanel = (GGraph)GetChild("categoryPanel");
            m_CategoryTitle = (GTextField)GetChild("categoryTitle");
            m_AllButton = (UICategoryTabButton)GetChild("allButton");
            m_EquipmentButton = (UICategoryTabButton)GetChild("equipmentButton");
            m_ConsumableButton = (UICategoryTabButton)GetChild("consumableButton");
            m_QuestButton = (UICategoryTabButton)GetChild("questButton");
            m_ControllerLabel = (GTextField)GetChild("controllerLabel");
            m_ControllerPageText = (GTextField)GetChild("controllerPageText");
            m_ContentPanel = (GGraph)GetChild("contentPanel");
            m_ListTitle = (GTextField)GetChild("listTitle");
            m_StatusText = (GTextField)GetChild("statusText");
            m_ItemList = (GList)GetChild("itemList");
            m_HintLine = (GGraph)GetChild("hintLine");
            m_HintText = (GTextField)GetChild("hintText");
        }
    }
}