// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIMainView : GComponent
    {
        private GGraph m_Background;
        public GGraph Background => this.m_Background;
        private GGraph m_Topbar;
        public GGraph Topbar => this.m_Topbar;
        private GGraph m_Accent;
        public GGraph Accent => this.m_Accent;
        private GTextField m_Title;
        public GTextField Title => this.m_Title;
        private GTextField m_Subtitle;
        public GTextField Subtitle => this.m_Subtitle;
        private UIActionButton m_OpenInventoryButton;
        public UIActionButton OpenInventoryButton => this.m_OpenInventoryButton;
        private UIRefreshButton m_RefreshButton;
        public UIRefreshButton RefreshButton => this.m_RefreshButton;
        private GTextField m_SectionTitle;
        public GTextField SectionTitle => this.m_SectionTitle;
        private GGraph m_StatusPanel;
        public GGraph StatusPanel => this.m_StatusPanel;
        private GGraph m_StatusDot;
        public GGraph StatusDot => this.m_StatusDot;
        private GTextField m_StatusLabel;
        public GTextField StatusLabel => this.m_StatusLabel;
        private GTextField m_StatusText;
        public GTextField StatusText => this.m_StatusText;
        private GTextField m_StatusDetail;
        public GTextField StatusDetail => this.m_StatusDetail;
        private GGraph m_StatusLine;
        public GGraph StatusLine => this.m_StatusLine;
        private GTextField m_MetricsTitle;
        public GTextField MetricsTitle => this.m_MetricsTitle;
        private GGraph m_MetricsPanel;
        public GGraph MetricsPanel => this.m_MetricsPanel;
        private GTextField m_CheckLabel;
        public GTextField CheckLabel => this.m_CheckLabel;
        private GTextField m_CheckCountText;
        public GTextField CheckCountText => this.m_CheckCountText;
        private GTextField m_CheckUnit;
        public GTextField CheckUnit => this.m_CheckUnit;
        private GGraph m_MetricLine;
        public GGraph MetricLine => this.m_MetricLine;
        private GTextField m_PackageKey;
        public GTextField PackageKey => this.m_PackageKey;
        private GTextField m_PackageValue;
        public GTextField PackageValue => this.m_PackageValue;
        private GTextField m_ViewKey;
        public GTextField ViewKey => this.m_ViewKey;
        private GTextField m_ViewValue;
        public GTextField ViewValue => this.m_ViewValue;
        private GTextField m_FlowTitle;
        public GTextField FlowTitle => this.m_FlowTitle;
        private GGraph m_FlowBand;
        public GGraph FlowBand => this.m_FlowBand;
        private GGraph m_Step1;
        public GGraph Step1 => this.m_Step1;
        private GTextField m_Step1Number;
        public GTextField Step1Number => this.m_Step1Number;
        private GTextField m_Step1Title;
        public GTextField Step1Title => this.m_Step1Title;
        private GTextField m_Step1Detail;
        public GTextField Step1Detail => this.m_Step1Detail;
        private GGraph m_Step2;
        public GGraph Step2 => this.m_Step2;
        private GTextField m_Step2Number;
        public GTextField Step2Number => this.m_Step2Number;
        private GTextField m_Step2Title;
        public GTextField Step2Title => this.m_Step2Title;
        private GTextField m_Step2Detail;
        public GTextField Step2Detail => this.m_Step2Detail;
        private GGraph m_Arrow1;
        public GGraph Arrow1 => this.m_Arrow1;
        private GGraph m_Arrow2;
        public GGraph Arrow2 => this.m_Arrow2;
        private GGraph m_Arrow3;
        public GGraph Arrow3 => this.m_Arrow3;
        private GGraph m_Step3;
        public GGraph Step3 => this.m_Step3;
        private GTextField m_Step3Number;
        public GTextField Step3Number => this.m_Step3Number;
        private GTextField m_Step3Title;
        public GTextField Step3Title => this.m_Step3Title;
        private GTextField m_Step3Detail;
        public GTextField Step3Detail => this.m_Step3Detail;
        private GGraph m_Step4;
        public GGraph Step4 => this.m_Step4;
        private GTextField m_Step4Number;
        public GTextField Step4Number => this.m_Step4Number;
        private GTextField m_Step4Title;
        public GTextField Step4Title => this.m_Step4Title;
        private GTextField m_Step4Detail;
        public GTextField Step4Detail => this.m_Step4Detail;
        private GTextField m_Footer;
        public GTextField Footer => this.m_Footer;
        public const string URL = "ui://oozeu71h7xe70";

        public static UIMainView CreateInstance()
        {
            return (UIMainView)UIPackage.CreateObject("Package1", "MainView");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Background = (GGraph)GetChild("background");
            m_Topbar = (GGraph)GetChild("topbar");
            m_Accent = (GGraph)GetChild("accent");
            m_Title = (GTextField)GetChild("title");
            m_Subtitle = (GTextField)GetChild("subtitle");
            m_OpenInventoryButton = (UIActionButton)GetChild("openInventoryButton");
            m_RefreshButton = (UIRefreshButton)GetChild("refreshButton");
            m_SectionTitle = (GTextField)GetChild("sectionTitle");
            m_StatusPanel = (GGraph)GetChild("statusPanel");
            m_StatusDot = (GGraph)GetChild("statusDot");
            m_StatusLabel = (GTextField)GetChild("statusLabel");
            m_StatusText = (GTextField)GetChild("statusText");
            m_StatusDetail = (GTextField)GetChild("statusDetail");
            m_StatusLine = (GGraph)GetChild("statusLine");
            m_MetricsTitle = (GTextField)GetChild("metricsTitle");
            m_MetricsPanel = (GGraph)GetChild("metricsPanel");
            m_CheckLabel = (GTextField)GetChild("checkLabel");
            m_CheckCountText = (GTextField)GetChild("checkCountText");
            m_CheckUnit = (GTextField)GetChild("checkUnit");
            m_MetricLine = (GGraph)GetChild("metricLine");
            m_PackageKey = (GTextField)GetChild("packageKey");
            m_PackageValue = (GTextField)GetChild("packageValue");
            m_ViewKey = (GTextField)GetChild("viewKey");
            m_ViewValue = (GTextField)GetChild("viewValue");
            m_FlowTitle = (GTextField)GetChild("flowTitle");
            m_FlowBand = (GGraph)GetChild("flowBand");
            m_Step1 = (GGraph)GetChild("step1");
            m_Step1Number = (GTextField)GetChild("step1Number");
            m_Step1Title = (GTextField)GetChild("step1Title");
            m_Step1Detail = (GTextField)GetChild("step1Detail");
            m_Step2 = (GGraph)GetChild("step2");
            m_Step2Number = (GTextField)GetChild("step2Number");
            m_Step2Title = (GTextField)GetChild("step2Title");
            m_Step2Detail = (GTextField)GetChild("step2Detail");
            m_Arrow1 = (GGraph)GetChild("arrow1");
            m_Arrow2 = (GGraph)GetChild("arrow2");
            m_Arrow3 = (GGraph)GetChild("arrow3");
            m_Step3 = (GGraph)GetChild("step3");
            m_Step3Number = (GTextField)GetChild("step3Number");
            m_Step3Title = (GTextField)GetChild("step3Title");
            m_Step3Detail = (GTextField)GetChild("step3Detail");
            m_Step4 = (GGraph)GetChild("step4");
            m_Step4Number = (GTextField)GetChild("step4Number");
            m_Step4Title = (GTextField)GetChild("step4Title");
            m_Step4Detail = (GTextField)GetChild("step4Detail");
            m_Footer = (GTextField)GetChild("footer");
        }
    }
}