// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.FairyGUI.Package1
{
    public partial class UIRuntimeInspectorView : GComponent
    {
        private GButton m_CloseButton;
        public GButton CloseButton => this.m_CloseButton;
        public const string URL = "ui://oozeu71hq84t8";

        public static UIRuntimeInspectorView CreateInstance()
        {
            return (UIRuntimeInspectorView)UIPackage.CreateObject("Package1", "RuntimeInspectorView");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_CloseButton = (GButton)GetChild("closeButton");
        }
    }
}