// <auto-generated />
// Generated by Tools/FairyGUI/Generate-FairyPackageBinderRegistry.ps1. Do not edit.

using Game;
using GameFramework;

namespace Game.FairyGUI
{
    public static class FairyPackageBinderRegistryGenerated
    {
        public static void BindAllPackages(FairyUIFormDescriptor descriptor)
        {
            switch (descriptor.PackageName)
            {
                case "Package1":
                    break;
                default:
                    throw new GameFrameworkException(
                        $"No FairyGUI package binder is registered for UI '{descriptor.CsName}' " +
                        $"(id {descriptor.UiId}, package '{descriptor.PackageName}').");
            }

            global::Game.FairyGUI.Package1.Package1Binder.BindAll();
        }
    }
}
