
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRInventory :  Luban.EditorBeanBase 
{
    public DRInventory()
    {
            Name = "";
            Description = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Name"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Name = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Category"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Category = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Count"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Count = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Description"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Description = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (Name == null) { throw new System.ArgumentNullException(); }
            _json["Name"] = new JSONString(Name);
        }
        {
            _json["Category"] = new JSONNumber(Category);
        }
        {
            _json["Count"] = new JSONNumber(Count);
        }
        {

            if (Description == null) { throw new System.ArgumentNullException(); }
            _json["Description"] = new JSONString(Description);
        }
    }

    public static DRInventory LoadJsonDRInventory(JSONNode _json)
    {
        DRInventory obj = new DRInventory();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRInventory(DRInventory _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// 物品编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 物品名称
    /// </summary>
    public string Name;

    /// <summary>
    /// 分类
    /// </summary>
    public int Category;

    /// <summary>
    /// 数量
    /// </summary>
    public int Count;

    /// <summary>
    /// 描述
    /// </summary>
    public string Description;

}
}

