// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;

namespace Game.Hot.FairyGUI.Package1
{
    public class Package1Binder
    {
        public static void BindAll()
        {
            UIObjectFactory.SetPackageItemExtension(UIMainView.URL, typeof(UIMainView));
            UIObjectFactory.SetPackageItemExtension(UIRefreshButton.URL, typeof(UIRefreshButton));
        }
    }
}