// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.Hot.FairyGUI.Package1
{
    public partial class UIInventoryOverlayView : GComponent
    {
        private GGraph m_Background;
        public GGraph Background => this.m_Background;
        private GGraph m_Panel;
        public GGraph Panel => this.m_Panel;
        private GTextField m_TitleText;
        public GTextField TitleText => this.m_TitleText;
        private GTextField m_DetailText;
        public GTextField DetailText => this.m_DetailText;
        private UIActionButton m_CloseButton;
        public UIActionButton CloseButton => this.m_CloseButton;
        public const string URL = "ui://oozeu71hi20a4";

        public static UIInventoryOverlayView CreateInstance()
        {
            return (UIInventoryOverlayView)UIPackage.CreateObject("Package1", "InventoryOverlayView");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_Background = (GGraph)GetChild("background");
            m_Panel = (GGraph)GetChild("panel");
            m_TitleText = (GTextField)GetChild("titleText");
            m_DetailText = (GTextField)GetChild("detailText");
            m_CloseButton = (UIActionButton)GetChild("closeButton");
        }
    }
}