// This is automatically generated by FairyGUI. Please do not modify it.

using FairyGUI;
using FairyGUI.Utils;

namespace Game.Hot.FairyGUI.Package1
{
    public partial class UIItemDetailWindow : GComponent
    {
        private GGraph m_WindowFrame;
        public GGraph WindowFrame => this.m_WindowFrame;
        private GGraph m_WindowTopbar;
        public GGraph WindowTopbar => this.m_WindowTopbar;
        private GTextField m_TitleText;
        public GTextField TitleText => this.m_TitleText;
        private GTextField m_FocusTokenText;
        public GTextField FocusTokenText => this.m_FocusTokenText;
        private GTextField m_ItemNameText;
        public GTextField ItemNameText => this.m_ItemNameText;
        private GTextField m_ItemTypeText;
        public GTextField ItemTypeText => this.m_ItemTypeText;
        private GGraph m_DetailLine;
        public GGraph DetailLine => this.m_DetailLine;
        private GTextField m_DescriptionText;
        public GTextField DescriptionText => this.m_DescriptionText;
        private GTextField m_FocusStatusText;
        public GTextField FocusStatusText => this.m_FocusStatusText;
        private UIActionButton m_OpenOverlayButton;
        public UIActionButton OpenOverlayButton => this.m_OpenOverlayButton;
        private UIActionButton m_CloseButton;
        public UIActionButton CloseButton => this.m_CloseButton;
        public const string URL = "ui://oozeu71hi20a3";

        public static UIItemDetailWindow CreateInstance()
        {
            return (UIItemDetailWindow)UIPackage.CreateObject("Package1", "ItemDetailWindow");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            m_WindowFrame = (GGraph)GetChild("windowFrame");
            m_WindowTopbar = (GGraph)GetChild("windowTopbar");
            m_TitleText = (GTextField)GetChild("titleText");
            m_FocusTokenText = (GTextField)GetChild("focusTokenText");
            m_ItemNameText = (GTextField)GetChild("itemNameText");
            m_ItemTypeText = (GTextField)GetChild("itemTypeText");
            m_DetailLine = (GGraph)GetChild("detailLine");
            m_DescriptionText = (GTextField)GetChild("descriptionText");
            m_FocusStatusText = (GTextField)GetChild("focusStatusText");
            m_OpenOverlayButton = (UIActionButton)GetChild("openOverlayButton");
            m_CloseButton = (UIActionButton)GetChild("closeButton");
        }
    }
}