// <auto-generated />
// Generated by FairyUIPresenterRegistryCodeGenerator. Do not edit.

using System;
using System.Collections.Generic;
using Game;

namespace Game.Hot
{
    internal static class FairyUIPresenterRegistryGenerated
    {
        public static IReadOnlyDictionary<int, Func<IFairyUIPresenter>> CreateFactories()
        {
            return new Dictionary<int, Func<IFairyUIPresenter>>
            {
                { UIFormId.DialogForm, static () => new global::Game.Hot.FairyDialogForm() },
                { UIFormId.FairyDemoForm, static () => new global::Game.Hot.FairyDemoForm() },
                { UIFormId.FairyInventoryForm, static () => new global::Game.Hot.FairyInventoryForm() },
                { UIFormId.FairyItemDetailForm, static () => new global::Game.Hot.FairyItemDetailForm() },
                { UIFormId.FairyInventoryOverlayForm, static () => new global::Game.Hot.FairyInventoryOverlayForm() },
                { UIFormId.FairyRuntimeInspectorForm, static () => new global::Game.Hot.FairyRuntimeInspectorForm() },
            };
        }
    }
}
