
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRInventory : Luban.BeanBase
{
    public DRInventory(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Category = _buf.ReadInt();
        Count = _buf.ReadInt();
        Description = _buf.ReadString();
        PostInit();
    }

    public static DRInventory DeserializeDRInventory(ByteBuf _buf)
    {
        return new DRInventory(_buf);
    }

    /// <summary>
    /// 物品编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 分类
    /// </summary>
    public readonly int Category;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    public const int __ID__ = -884477842;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Category:" + Category + ","
        + "Count:" + Count + ","
        + "Description:" + Description + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
